# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoTemporal < Formula
  desc "protoc-gen-go_temporal - a protoc plugin for generating Temporal clients, workers, and clis in go from protobuf schemas"
  homepage "https://github.com/cludden/protoc-gen-go-temporal"
  version "1.0.2-rc.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.0.2-rc.0/protoc-gen-go_temporal_1.0.2-rc.0_darwin_arm64.tar.gz"
      sha256 "57a809e187f53646b9b7f3c6ffb2069811555bf333c3c64060f3990d181e9573"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.0.2-rc.0/protoc-gen-go_temporal_1.0.2-rc.0_darwin_amd64.tar.gz"
      sha256 "0c60b8ea0ed7d75d3a10841c3bcfebed8d6984251b712a55c85fdd4eb13c4887"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.0.2-rc.0/protoc-gen-go_temporal_1.0.2-rc.0_linux_arm64.tar.gz"
      sha256 "72e5f3b3e5954015b0d66039e6da7e06f997c03a17f37bfee16b66b51feba5ae"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.0.2-rc.0/protoc-gen-go_temporal_1.0.2-rc.0_linux_amd64.tar.gz"
      sha256 "c6d1d58342e305634f3572a3d4fa1d745b3cbc93efe41ae72da8976dd9261ea0"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
  end
end
