# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoTemporal < Formula
  desc "protoc-gen-go_temporal - a protoc plugin for generating Temporal clients, workers, and clis in go from protobuf schemas"
  homepage "https://github.com/cludden/protoc-gen-go-temporal"
  version "1.10.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.10.4/protoc-gen-go_temporal_1.10.4_darwin_amd64.tar.gz"
      sha256 "fa8f73877ca31cac5abb06b052d2a9a578bc861680bd8f50f914558938fc4f11"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.10.4/protoc-gen-go_temporal_1.10.4_darwin_arm64.tar.gz"
      sha256 "24d497c0409b177e8e5e0f554f0dc9360ac956dd969d1461d473ab98cdc7ff24"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.10.4/protoc-gen-go_temporal_1.10.4_linux_amd64.tar.gz"
      sha256 "bc506e0b98295cb1d78d1750c2ef7d7869b02a51432f6aa6891a3b5ca6ce83bc"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.10.4/protoc-gen-go_temporal_1.10.4_linux_arm64.tar.gz"
      sha256 "6e38d66fe1e0756421a8b88318d0b8c2f8e0a248fcec89a9127aec864d667f1a"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
  end
end
