# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoTemporal < Formula
  desc "protoc-gen-go_temporal - a protoc plugin for generating Temporal clients, workers, and clis in go from protobuf schemas"
  homepage "https://github.com/cludden/protoc-gen-go-temporal"
  version "1.13.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.13.1/protoc-gen-go_temporal_1.13.1_darwin_amd64.tar.gz"
      sha256 "cdca810eaa435bd70542c0c164f1d5abe61803c5657bde69c82849d1e7fe3858"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
    on_arm do
      url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.13.1/protoc-gen-go_temporal_1.13.1_darwin_arm64.tar.gz"
      sha256 "8e7ac4bc47a1b7cd1c9ec47c2b5514d434ac7f5301f80e9af763a45556a5b1da"

      def install
        bin.install "protoc-gen-go_temporal"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.13.1/protoc-gen-go_temporal_1.13.1_linux_amd64.tar.gz"
        sha256 "dc35ff6b296c792af9ab4f898e32b8dc82a6830e6023a5b28740448aa9c19d13"

        def install
          bin.install "protoc-gen-go_temporal"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cludden/protoc-gen-go-temporal/releases/download/v1.13.1/protoc-gen-go_temporal_1.13.1_linux_arm64.tar.gz"
        sha256 "f56f95585cacc16dd374c0798b751b9c5fecea3b1aca5c1d9898fed867d90927"

        def install
          bin.install "protoc-gen-go_temporal"
        end
      end
    end
  end
end
